version: "3.9"

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: h2-db
    ports:
      - "9092:9092"
    volumes:
      - h2-data:/opt/h2-data
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
    environment:
      H2_BASE_DIR: /opt/h2-data

  web:
    build:
      context: ../CA2-part2/rest
      dockerfile: dockerfile-multi-stage
    container_name: spring-web
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://db:9092/./payrolldb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    ports:
      - "8080:8080"

volumes:
  h2-data:
