- hosts: production
  gather_facts: no
  tasks:
    - name: Check Spring Boot health (simple root endpoint)
      uri:
        url: http://localhost:8080/
        status_code: 200,404
      register: result
      retries: 10
      delay: 3
      until: result.status in [200, 404]
