- hosts: green
  gather_facts: no
  tasks:
    - name: Check Spring Boot health endpoint
      uri:
        url: http://localhost:8080/actuator/health
        status_code: 200
      register: result
      retries: 10
      delay: 3
      until: result.status == 200
