name: CA6 Part1 CI/CD (GitHub Actions)

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-test:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Assemble (Gradle build)
        working-directory: CA6/spring-example
        run: |
          ./gradlew clean build

      - name: Test
        working-directory: CA6/spring-example
        run: |
          ./gradlew test

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: CA6/spring-example/build/libs/*.jar

  deploy:
    needs: build-test
    runs-on: self-hosted
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: CA6/spring-example/build/libs

      - name: Normalize JAR name (usar JAR executável)
        working-directory: CA6/spring-example/build/libs
        run: |
          echo "Conteúdo da pasta de JARs:"
          ls -l

          # pega o JAR *sem* '-plain'
          JAR=$(ls spring-example-*-SNAPSHOT.jar | grep -v plain | head -n 1)

          echo "Usando JAR: $JAR"
          cp "$JAR" app.jar

      - name: Deploy to GREEN with Ansible
        working-directory: CA6/alternativa
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/deploy.yml --limit green

      - name: Health check from runner
        run: |
          curl -f http://192.168.56.11:8080/employees

      - name: Create stable tag and save artifact for rollback
        if: success()
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          VERSION="stable-v${{ github.run_number }}"
          echo "Criando tag $VERSION"
          git tag "$VERSION"
          git push origin "$VERSION"

          echo "A guardar artefacto para rollback como app-${VERSION}.jar"
          mkdir -p CA6/alternativa/artifacts
          cp CA6/spring-example/build/libs/app.jar CA6/alternativa/artifacts/app-${VERSION}.jar
