name: CA6 Part1 Rollback (GitHub Actions)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Stable tag (ex: stable-v5)'
        required: true

permissions:
  contents: write

jobs:
  rollback:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Preparar artefacto de rollback
        run: |
          mkdir -p CA6/alternativa/artifacts

          echo "A copiar artefacto est√°vel: app-${{ github.event.inputs.tag }}.jar"

          cp CA6/alternativa/artifacts/app-${{ github.event.inputs.tag }}.jar \
             CA6/alternativa/app.jar

      - name: Executar playbook de rollback
        working-directory: CA6/alternativa
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/rollback.yml \
            --extra-vars "tag=${{ github.event.inputs.tag }}"
